# Generated by Django 6.0.4 on 2026-05-31 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=10)),
                ('payment_type', models.CharField(choices=[('payment', 'Payment'), ('fine', 'Fine')], max_length=10)),
                ('session_url', models.URLField()),
                ('session_id', models.CharField()),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrowing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowings.borrowing')),
            ],
        ),
    ]
